I dont know anymore

diff --git a/repo/ClassicAppleBoot/DEBIAN/postrm b/repo/ClassicAppleBoot/DEBIAN/postrm
--- a/repo/ClassicAppleBoot/DEBIAN/postrm
+++ b/repo/ClassicAppleBoot/DEBIAN/postrm
@@ -3,8 +3,8 @@ echo "The backup made before installation will now be restored..."
 set -e
 cd "/"
 echo "Restoring files from /Library/Application Support/ClassicAppleBoot..."
-sudo mv -f "/Library/Application Support/ClassicAppleBoot/apple-logo-black-n84@2x~iphone.png" "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/" || echo "Failed to restore backup!"
-sudo mv -f "/Library/Application Support/ClassicAppleBoot/apple-logo-black@2x~iphone.png" "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/" || echo "Failed to restore backup!"
+mv -f "/Library/Application Support/ClassicAppleBoot/apple-logo-black-n84@2x~iphone.png" "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/" || echo "Failed to restore backup!"
+mv -f "/Library/Application Support/ClassicAppleBoot/apple-logo-black@2x~iphone.png" "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/" || echo "Failed to restore backup!"
 echo "Removing backup folder..."
-sudo rmdir "/Library/Application Support/ClassicAppleBoot/" || set -e && echo "Failed to remove directory!"
+rmdir "/Library/Application Support/ClassicAppleBoot/" || set -e && echo "Failed to remove directory!"
 echo "Finished restoring the backup!"
