Forece these motherfuckers to move files

diff --git a/repo/ClassicAppleBoot/DEBIAN/postrm b/repo/ClassicAppleBoot/DEBIAN/postrm
--- a/repo/ClassicAppleBoot/DEBIAN/postrm
+++ b/repo/ClassicAppleBoot/DEBIAN/postrm
@@ -2,8 +2,8 @@
 echo "The backup made before installation will now be restored..."
 cd "/"
 echo "Restoring files from /Library/Application Support/ClassicAppleBoot..."
-mv "/Library/Application Support/ClassicAppleBoot/apple-logo-black-n84@2x~iphone.png" "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/apple-logo-black-n84@2x~iphone.png" || set -e && echo "Failed backup!"
-mv "/Library/Application Support/ClassicAppleBoot/apple-logo-black@2x~iphone.png" "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/apple-logo-black@2x~iphone.png" || set -e && echo "Failed backup!"
+mv -f "/Library/Application Support/ClassicAppleBoot/apple-logo-black-n84@2x~iphone.png" "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/" || set -e && echo "Failed backup!"
+mv -f "/Library/Application Support/ClassicAppleBoot/apple-logo-black@2x~iphone.png" "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/" || set -e && echo "Failed backup!"
 echo "Removing backup folder..."
 rmdir "/Library/Application Support/ClassicAppleBoot/" || set -e
 echo "Finished restoring the backup!"
diff --git a/repo/ClassicAppleBoot/DEBIAN/preinst b/repo/ClassicAppleBoot/DEBIAN/preinst
--- a/repo/ClassicAppleBoot/DEBIAN/preinst
+++ b/repo/ClassicAppleBoot/DEBIAN/preinst
@@ -4,6 +4,6 @@ cd "/"
 echo "Creating backup directory in /Library/Application Support/ClassicAppleBoot/..."
 mkdir "/Library/Application Support/ClassicAppleBoot" || set -e
 echo "Copying over files..."
-mv "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/apple-logo-black-n84@2x~iphone.png" "/Library/Application Support/ClassicAppleBoot/apple-logo-black-n84@2x~iphone.png" || set -e && echo "Failed backup!"
-mv "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/apple-logo-black@2x~iphone.png" "/Library/Application Support/ClassicAppleBoot/apple-logo-black@2x~iphone.png" || set -e && echo "Failed backup!"
+mv -f "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/apple-logo-black-n84@2x~iphone.png" "/Library/Application Support/ClassicAppleBoot/" || set -e && echo "Failed backup!"
+mv -f "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/apple-logo-black@2x~iphone.png" "/Library/Application Support/ClassicAppleBoot/" || set -e && echo "Failed backup!"
 echo "Finished backing up!"
