Frickin' root

diff --git a/repo/ClassicAppleBoot/DEBIAN/postrm b/repo/ClassicAppleBoot/DEBIAN/postrm
--- a/repo/ClassicAppleBoot/DEBIAN/postrm
+++ b/repo/ClassicAppleBoot/DEBIAN/postrm
@@ -2,8 +2,8 @@
 echo "The backup made before installation will now be restored..."
 cd "/"
 echo "Restoring files from /Library/Application Support/ClassicAppleBoot..."
-mv -f "/Library/Application Support/ClassicAppleBoot/apple-logo-black-n84@2x~iphone.png" "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/" || set -e && echo "Failed backup!"
-mv -f "/Library/Application Support/ClassicAppleBoot/apple-logo-black@2x~iphone.png" "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/" || set -e && echo "Failed backup!"
+sudo mv -f "/Library/Application Support/ClassicAppleBoot/apple-logo-black-n84@2x~iphone.png" "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/" || set -e && echo "Failed to restore backup!"
+sudo mv -f "/Library/Application Support/ClassicAppleBoot/apple-logo-black@2x~iphone.png" "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/" || set -e && echo "Failed to restore backup!"
 echo "Removing backup folder..."
-rmdir "/Library/Application Support/ClassicAppleBoot/" || set -e
+sudo rmdir "/Library/Application Support/ClassicAppleBoot/" || set -e && echo "Failed to remove directory!"
 echo "Finished restoring the backup!"
diff --git a/repo/ClassicAppleBoot/DEBIAN/preinst b/repo/ClassicAppleBoot/DEBIAN/preinst
--- a/repo/ClassicAppleBoot/DEBIAN/preinst
+++ b/repo/ClassicAppleBoot/DEBIAN/preinst
@@ -2,8 +2,8 @@
 echo "The regular boot logo will be backed up before installing..."
 cd "/"
 echo "Creating backup directory in /Library/Application Support/ClassicAppleBoot/..."
-mkdir "/Library/Application Support/ClassicAppleBoot" || set -e
+sudo mkdir "/Library/Application Support/ClassicAppleBoot" || set -e && echo "Failed to create backup directory!"
 echo "Copying over files..."
-mv -f "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/apple-logo-black-n84@2x~iphone.png" "/Library/Application Support/ClassicAppleBoot/" || set -e && echo "Failed backup!"
-mv -f "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/apple-logo-black@2x~iphone.png" "/Library/Application Support/ClassicAppleBoot/" || set -e && echo "Failed backup!"
+sudo mv -f "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/apple-logo-black-n84@2x~iphone.png" "/Library/Application Support/ClassicAppleBoot/" || set -e && echo "Failed to backup files!"
+sudo mv -f "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/apple-logo-black@2x~iphone.png" "/Library/Application Support/ClassicAppleBoot/" || set -e && echo "Failed to backup files!"
 echo "Finished backing up!"
