Fix typo

diff --git a/repo/ClassicAppleBoot/DEBIAN/preinst b/repo/ClassicAppleBoot/DEBIAN/preinst
--- a/repo/ClassicAppleBoot/DEBIAN/preinst
+++ b/repo/ClassicAppleBoot/DEBIAN/preinst
@@ -5,6 +5,6 @@ cd "/"
 echo "Creating backup directory in /Library/Application Support/ClassicAppleBoot/..."
 mkdir "/Library/Application Support/ClassicAppleBoot" || echo "Failed to create backup directory!"
 echo "Copying over files..."
-mv -f "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/apple-logo-black-n84@2x~iphone.png" "/Library/Application Support/ClassicAppleBoot/" || echo "Failed to backup files!"
-mv -f "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/apple-logo-black@2x~iphone.png" "/Library/Application Support/ClassicAppleBoot/" || echo "Failed to backup files!"
+mv -f "/System/Library/PrivateFrameworks/ProgressUI.framework/apple-logo-black-n84@2x~iphone.png" "/Library/Application Support/ClassicAppleBoot/" || echo "Failed to backup files!"
+mv -f "/System/Library/PrivateFrameworks/ProgressUI.framework/apple-logo-black@2x~iphone.png" "/Library/Application Support/ClassicAppleBoot/" || echo "Failed to backup files!"
 echo "Finished backing up!"
