Hotfix pt. 11

diff --git a/repo/ClassicAppleBoot/DEBIAN/preinst b/repo/ClassicAppleBoot/DEBIAN/preinst
--- a/repo/ClassicAppleBoot/DEBIAN/preinst
+++ b/repo/ClassicAppleBoot/DEBIAN/preinst
@@ -1,9 +1,10 @@
 #!/bin/bash
 echo "The regular boot logo will be backed up before installing..."
+set -e
 cd "/"
 echo "Creating backup directory in /Library/Application Support/ClassicAppleBoot/..."
-sudo mkdir "/Library/Application Support/ClassicAppleBoot" || set -e && echo "Failed to create backup directory!"
+sudo mkdir "/Library/Application Support/ClassicAppleBoot" || echo "Failed to create backup directory!"
 echo "Copying over files..."
-sudo mv -f "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/apple-logo-black-n84@2x~iphone.png" "/Library/Application Support/ClassicAppleBoot/" || set -e && echo "Failed to backup files!"
-sudo mv -f "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/apple-logo-black@2x~iphone.png" "/Library/Application Support/ClassicAppleBoot/" || set -e && echo "Failed to backup files!"
+sudo mv -f "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/apple-logo-black-n84@2x~iphone.png" "/Library/Application Support/ClassicAppleBoot/" || echo "Failed to backup files!"
+sudo mv -f "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/apple-logo-black@2x~iphone.png" "/Library/Application Support/ClassicAppleBoot/" || echo "Failed to backup files!"
 echo "Finished backing up!"
